birth_date = input("enter your birthdate")
current_year = input("enter current year")
print(f"birthdate : {birth_date}")
print(f"current_year : {current_year}")
print("_"*20)
print(f"birth_year : {birth_date[0:4]}")
print(f"birth_month : {birth_date[5:7]}")
print(f"birth_day : {birth_date[7:]}")
age = int(current_year) - int(birth_date[0:4])
print(f"age : {age}")
